calc/urls.py
from django.conf.urls import url

from calc import views

urlpatterns = [
    url(r'^injection/$', views.calc_injection, name='injection'),
    url(r'^cri/simple/$', views.calc_cri_simple, name='cri_simple'),
    url(r'^cri/advanced/$', views.calc_cri_advanced, name='cri_advanced'),
    url(r'^cri/insulin/$', views.calc_cri_insulin, name='cri_insulin'),
    url(r'^cri/cpr/$', views.calc_cri_cpr, name='cri_cpr'),
    url(r'^cri/metoclopramide/', views.calc_cri_metoclopramide, name='cri_metoclopramide'),
]

vetcalc/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView
from django.contrib import admin

from common import views as common_views
from calc import urls as calc_urls
from info import urls as info_urls
from treatment_sheets import urls as tx_sheet_urls

urlpatterns = [
    url(r'^$', common_views.HomePageView.as_view(), name='home'),
    url(r'^calc/', include(calc_urls)),
    url(r'^info/', include(info_urls)),
    url(r'^tx_sheet/', include(tx_sheet_urls)),
    url(r'^disclaimer/', TemplateView.as_view(template_name='disclaimer.html'), name='disclaimer'),
    # url(r'^accounts/profile/$', )
    url(r'^accounts/', include('allauth.urls')),
    url(r'^admin/', admin.site.urls),
]

treatment_sheets/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings

from common.models import Prescription


class TxSheet(models.Model):
    """Treatment sheets for patients

    Fields:
        owner: user who created the treatment sheet
        name: name of the patient
        comment: whatever the tech chooses to enter
        date: date the treatment sheet was created

    """
    owner = models.ForeignKey(settings.AUTH_USER_MODEL)
    name = models.CharField(max_length=140, default='')
    comment = models.TextField(max_length=10000, default='')
    date = models.DateField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('view_tx_sheet', args=[self.id])

    def __str__(self):
        return self.name + ': ' + ((self.comment[:75] + '...') if len(self.comment) > 75 else self.comment)


class TxItem(models.Model):
    """Treatment sheet item

    Is related to :model:`treatment_sheets.TxSheet`.

    Fields:
        sheet: the treatment sheet the item belongs to
        med: the chosen med for the item
        dose: numerical dosage of the med
        freq: how often the med is taken per day
        unit: the unit that the dosage is in
        instruction: generated when the item is saved.  human readable instructions for the client.

    """

    FREQ_CHOICES = (
        ('SID', 'SID'),
        ('BID', 'BID')
    )

    UNIT_CHOICES = (
        ('mL', 'mLs'),
        ('C', 'capsules'),
        ('T', 'tablets')
    )

    sheet = models.ForeignKey(TxSheet, on_delete=None, default=None)
    med = models.ForeignKey(Prescription, on_delete=None, default=None)
    dose = models.FloatField(default=0)
    freq = models.CharField(max_length=5, choices=FREQ_CHOICES, default='')
    unit = models.CharField(max_length=5, choices=UNIT_CHOICES, default='')
    instruction = models.TextField(default='')

    def output_instruction(self):
        frequency = ''

        if self.freq == 'SID':
            frequency = 'once a day'
        elif self.freq == 'BID':
            frequency = 'twice a day'

        self.instruction = 'Take {} {} of {} {}.'.format(self.dose, self.get_unit_display(), self.med, frequency)

    def get_absolute_url(self):
        return reverse('view_tx_sheet', args=[self.sheet.id])

    def save(self, *args, **kwargs):
        self.output_instruction()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.med.name

templates/tx_sheet/tx_sheet.html
{% extends 'base.html' %}

{% block title %}<title>Treatment Sheets | VetCalc</title>{% endblock %}

{% block content %}
    <div class="row">
        {% if user.is_authenticated %}
        <div class="col-md-12">
            <h1>Welcome, {{ user }}</h1>
            <p><a href="{% url 'new_tx_sheet' %}">Create a new treatment sheet</a> | <a href="{% url 'account_logout' %}">Log out</a></p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h3>Treatment Sheets</h3>
            <p><i>Treatment sheets are deleted 72 hours after creation</i></p>
            <hr>
            {% if user.txsheet_set.all|length > 0 %}
                <ul>
                {% for sheet in user.txsheet_set.all %}
                    <li><a href="{% url 'view_tx_sheet' sheet.id %}">{{ sheet }} </a>
                        <a href="{% url 'del_tx_sheet' sheet.id %}" class="delete_item">
                            <span title="Delete this sheet" class="glyphicon glyphicon-remove"></span></a></li>
                {% endfor %}
                </ul>
            {% else %}
                <i>No treatment sheets found</i>
            {% endif %}
        </div>
        {% else %}
        <div class="col-md-12">
            <h1>Slow your roll, homie</h1>
            <hr>
            <p>This feature requires you to <a href="{% url 'account_login' %}">log in</a>.</p>
        </div>
        {% endif %}
    </div>
{% endblock %}

templates/tx_sheet/tx_sheet_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            {% crispy form %}
        </div>
    </div>
{% endblock %}

templates/tx_sheet/tx_sheet_new.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}<title>Create A New Treatment Sheet | Vetcalc</title>{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <h3>Create a new treatment sheet</h3>
            <hr>
            <form method="post">
                {% csrf_token %}
                {{ sheet_form|crispy }}
                {{ item_form|crispy }}
                <input class="btn btn-primary" name="submit" value="Submit" type="submit">
            </form>
        </div>
    </div>
{% endblock %}

templates/tx_sheet/tx_sheet_view.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}<title>{{ sheet }} | VetCalc</title>{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <p><a href="{% url 'edit_tx_sheet' sheet.id %}">Edit treatment sheet information</a> | <a href="{% url 'output_pdf' sheet.id %}">Output this sheet as a PDF</a></p>
            <h1>{{ sheet.name }}</h1>
            <hr>
            <p>{{ sheet.comment|linebreaks }}</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h3>Medication</h3>
            <hr>
            <ul>
            {% for item in sheet.txitem_set.all %}
                <li>
                    <h4><a href="{% url 'info_pre' item.med.slug %}">{{ item }}</a> <a href="{% url 'del_item_tx_sheet' sheet.id item.id %}" class="delete_item">
                        <span title="Delete this item" class="glyphicon glyphicon-remove"></span></a></h4>
                    <ul>
                        <li>{{ item.instruction }}</li>
                        <li>{{ item.med.client_desc }}</li>
                    </ul>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h3>Add another medication</h3>
            <hr>
            {% crispy form %}
        </div>
    </div>

{% endblock %}